sudo: required

services:
  - docker

language: python

python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make package_vulnerability
  - make flake
  - make unit_test_coverage
  - make docker_build
  - make component_tests

after_success:
  - pipenv run codecov

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - DESTINATION_IMAGE_NAME="eu.gcr.io/census-rm-ci/rm/census-rm-pubsub"

branches:
  only:
    - master
