version: '3'
services:
  rabbitmq:
    container_name: rabbitmq-census-pubsub
    image: rabbitmq:3.6.10-management
    ports:
    - "35672:5672"
    - "49672:15672"

  pubsub-emulator:
    container_name: pubsub-emulator-census-pubsub
    image: bigtruedata/gcloud-pubsub-emulator
    ports:
    - "8539:8539"
    command: start --host-port 0.0.0.0:8539

  pubsub:
    container_name: census-pubsub
    build: .
    image: eu.gcr.io/census-rm-ci/rm/census-rm-pubsub:latest
    volumes:
      - /app
    external_links:
      - pubsub-emulator
      - rabbitmq
    restart: always
    healthcheck:
      test: bash -c "[ -f /app/pubsub-ready ]"
      interval: 5s
    environment:
    - RABBIT_HOST=rabbitmq
    - RABBIT_PORT=5672
    - RABBIT_VIRTUALHOST=/
    - RABBIT_USERNAME=guest
    - RABBIT_PASSWORD=guest
    - SUBSCRIPTION_PROJECT_ID=project
    - RECEIPT_TOPIC_PROJECT_ID=project
    - PUBSUB_EMULATOR_HOST=pubsub-emulator:8539
    - RABBIT_EXCHANGE=events
    - RABBIT_ROUTE=event.response.receipt
    - RECEIPT_TOPIC_NAME=eq-submission-topic
    - SUBSCRIPTION_NAME=rm-receipt-subscription
    - OFFLINE_RECEIPT_TOPIC_NAME=offline-receipt-topic
    - OFFLINE_SUBSCRIPTION_NAME=rm-offline-receipt-subscription
