version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6.10-management
    ports:
    - "34369:4369"
    - "55672:25672"
    - "35671:5671"
    - "35672:5672"
    - "46671:15671"
    - "46672:15672"

  pubsub-emulator:
    container_name: pubsub-emulator
    image: bigtruedata/gcloud-pubsub-emulator
    ports:
    - "8538:8538"
    command: start --host-port 0.0.0.0:8538

  pubsub:
    container_name: pubsub
    image: census-rm-pubsub:latest
    external_links:
      - pubsub-emulator
      - rabbitmq
    restart: always
    environment:
    - RABBIT_AMQP=amqp://guest:guest@rabbitmq:5672
    - SUBSCRIPTION_PROJECT_ID=project
    - RECEIPT_TOPIC_PROJECT_ID=project
    - PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
    - RABBIT_QUEUE=Case.Responses
    - RABBIT_EXCHANGE=case-outbound-exchange
    - RABBIT_ROUTE=Case.Responses.binding
    - RECEIPT_TOPIC_NAME=eq-submission-topic
    - SUBSCRIPTION_NAME=rm-receipt-subscription
